//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVC.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int p_no { get; set; }
        public string p_ad { get; set; }
        public string p_soyad { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public string dogum_yeri { get; set; }
        public Nullable<System.DateTime> ise_baslama_tarihi { get; set; }
        public Nullable<decimal> maas { get; set; }
        public Nullable<decimal> prim { get; set; }
        public Nullable<int> departmanID { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
